# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87ea1f37e4c974c37a0e70895b8fb04c87fbb5e384f980053eba816874a1ae790cfec811dd476fd415498cd48b29b3dc39c2797fbabf90ff15d7be4b33a28bdd

test:
  secret_key_base: d21327fce21c19c9526852880c1bfdbc3f95380c3611a3967739fb3aed9408f2fd898bf480ffb5dd46c029d79fc4b06ea7cc715f4126bcc0025f178eb925b51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
